#ifndef BODY_DEF
#define BODY_DEF
enum MYDIR{DIR_LEFT, DIR_RIGHT};

enum ABIL{ABIL_NONE, ABIL_TELE, ABIL_BOOST, ABIL_MORPH};

enum TYPE{TYPE_STATIC, TYPE_PASSIVE, TYPE_BODY, TYPE_PLAYER, TYPE_CHECKPOINT, TYPE_CORPSE, TYPE_HURT, TYPE_HURT_VIS};

#include "bodies.c"

#endif
